name: Deploy to Vercel

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
