name: Test Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret (logs masqués pour sécurité)
        run: |
          echo "PROJECT_PATH secret is set"
          echo "SSH_HOST secret is set"
          echo "SSH_PRIVATE_KEY secret is set"
          echo "SSH_USER secret is set"
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Test SSH connection
        run: |
          mkdir -p ~/.ssh                   # <-- créer le dossier
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Connexion OK'"