name: Test Secret

on:
  workflow_dispatch:  # permet de le lancer manuellement

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        run: |
          echo "Le secret est : $MY_SECRET"
          echo "Le secret est : $SSH_HOST"
          echo "Le secret est : $SSH_PRIVATE_KEY"
          echo "Le secret est : $SSH_USER"
        env:
          MY_SECRET: ${{ secrets.PROJECT_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        
      - name: Test SSH connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Connexion OK'"